<?php
define("INCLUDE_PATH","includes");
define("APP_PATH","app");
require("".INCLUDE_PATH."/config.php");
require("".INCLUDE_PATH."/header.php");
require("".INCLUDE_PATH."/menu.php");
require("".APP_PATH."/playlists_main.php");
require("".INCLUDE_PATH."/footer.php");
require("".INCLUDE_PATH."/modal.php");
 ?>
